CardName = str|object # card id or object id, e.g. "01001a", c1 (without quotes)

def Gain(*cards: CardName): ...
def Draw(num: int): ...
def ClearHand(): ...
def ClearHandFor(player_id: int): ...
def Ready(*cards: CardName): ...
def Exhaust(*cards: CardName): ...
def Discard(*cards: CardName): ...
def Remove(*cards: CardName): ...
def Flip(*cards: CardName): ...

def Heal(card: CardName, val: int): ...
def Damage(card: CardName, val: int): ...
def Confuse(card: CardName): ...
def Stun(card: CardName): ...
def Tough(card: CardName): ...
def ChangeForm(card: CardName): ...
def ChangeFormFor(player_id: int, rule: str): ...

def PlaceThreat(card: CardName, val:int): ...
def Counter(card: CardName, name: 'str', size: int): ...
def Token(card: CardName, name: 'str', size: int): ...

def Reveal(card: CardName): ...
def PutIntoPlay(card: CardName): ...
def PutIntoPlayFor(player_id: int, card: CardName): ...
def Boost(card: CardName): ...
def PutIntoDeck(*cards: CardName): ...

def End(message: str=""): ...

